name: Examen 3
on: 
  push:
    branches:
      - test_1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Print Something
      run: echo "Tirzah Peniche Barba"
    - name: Print Something 2
      run: node --version
    - name: Print Something 3
      run: echo "739502"